"""empty message

Revision ID: 66b7658b4c45
Revises: 
Create Date: 2024-03-26 10:48:40.393169

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '66b7658b4c45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_book',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('book_name', sa.String(length=100), nullable=True),
    sa.Column('cate_id', sa.Integer(), nullable=True),
    sa.Column('cate_name', sa.String(length=50), nullable=True),
    sa.Column('channel_type', sa.SmallInteger(), nullable=True),
    sa.Column('author_name', sa.String(length=50), nullable=True),
    sa.Column('chapter_num', sa.Integer(), nullable=True),
    sa.Column('is_publish', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('cover', sa.String(length=256), nullable=True),
    sa.Column('intro', mysql.TEXT(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('showed', sa.Boolean(), nullable=True),
    sa.Column('channel_name', sa.String(length=20), nullable=True),
    sa.Column('channel_url', sa.String(length=256), nullable=True),
    sa.Column('ranking', sa.Integer(), server_default='0', nullable=True),
    sa.Column('short_des', sa.String(length=50), server_default='', nullable=True),
    sa.Column('collect_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('heat', sa.Integer(), server_default='0', nullable=True),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_index(op.f('ix_tb_book_cate_id'), 'tb_book', ['cate_id'], unique=False)
    op.create_index(op.f('ix_tb_book_channel_type'), 'tb_book', ['channel_type'], unique=False)
    op.create_table('tb_book_category',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('cate_id', sa.Integer(), nullable=False),
    sa.Column('cate_name', sa.String(length=50), nullable=True),
    sa.Column('cate_icon', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('cate_id')
    )
    op.create_table('tb_book_chapter',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('volume_id', sa.Integer(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('chapter_name', sa.String(length=100), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_tb_book_chapter_book_id'), 'tb_book_chapter', ['book_id'], unique=False)
    op.create_index(op.f('ix_tb_book_chapter_chapter_id'), 'tb_book_chapter', ['chapter_id'], unique=False)
    op.create_table('tb_book_volume',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('volume_id', sa.Integer(), nullable=True),
    sa.Column('volume_name', sa.String(length=100), nullable=True),
    sa.Column('chapter_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_book_volume_book_id'), 'tb_book_volume', ['book_id'], unique=False)
    op.create_index(op.f('ix_tb_book_volume_volume_id'), 'tb_book_volume', ['volume_id'], unique=False)
    op.create_table('tb_read_rate',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('chapter_name', sa.String(length=100), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_search_keyword',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('is_hot', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('openId', sa.String(length=128), nullable=True),
    sa.Column('userName', sa.String(length=16), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('gender', sa.Integer(), server_default='0', nullable=True),
    sa.Column('province', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('district', sa.String(length=50), nullable=True),
    sa.Column('avatarUrl', sa.String(length=128), nullable=True),
    sa.Column('preference', sa.Integer(), server_default='0', nullable=True),
    sa.Column('brightness', sa.Integer(), server_default='30', nullable=True),
    sa.Column('fontSize', sa.Integer(), server_default='14', nullable=True),
    sa.Column('background', sa.String(length=10), server_default='B1', nullable=True),
    sa.Column('turn', sa.String(length=10), server_default='T1', nullable=True),
    sa.Column('last_read', sa.Integer(), nullable=True),
    sa.Column('last_read_chapter_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('openId'),
    sa.UniqueConstraint('userName')
    )
    op.create_table('tb_book_chapter_content',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', mysql.MEDIUMTEXT(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['tb_book_chapter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_book_shelf',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['tb_book.book_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tb_user.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'user_id')
    )
    op.create_table('tb_browse_history',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['tb_book.book_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tb_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_browse_history')
    op.drop_table('tb_book_shelf')
    op.drop_table('tb_book_chapter_content')
    op.drop_table('tb_user')
    op.drop_table('tb_search_keyword')
    op.drop_table('tb_read_rate')
    op.drop_index(op.f('ix_tb_book_volume_volume_id'), table_name='tb_book_volume')
    op.drop_index(op.f('ix_tb_book_volume_book_id'), table_name='tb_book_volume')
    op.drop_table('tb_book_volume')
    op.drop_index(op.f('ix_tb_book_chapter_chapter_id'), table_name='tb_book_chapter')
    op.drop_index(op.f('ix_tb_book_chapter_book_id'), table_name='tb_book_chapter')
    op.drop_table('tb_book_chapter')
    op.drop_table('tb_book_category')
    op.drop_index(op.f('ix_tb_book_channel_type'), table_name='tb_book')
    op.drop_index(op.f('ix_tb_book_cate_id'), table_name='tb_book')
    op.drop_table('tb_book')
    # ### end Alembic commands ###
